######################################################################
##
## Filename: czestotliwosci.udo
## Created on: Sun Apr 15 19:59:06 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
