######################################################################
##
## Filename: bin2bcd.udo
## Created on: Sat Apr 14 11:39:15 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
