######################################################################
##
## Filename: lab2.udo
## Created on: Mon Mar 26 19:46:37 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
