######################################################################
##
## Filename: counterlogic.udo
## Created on: Sun May 06 09:46:43 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
