######################################################################
##
## Filename: clk_gen_1M_sig.udo
## Created on: Sun May 06 19:12:39 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
