######################################################################
##
## Filename: log_data.udo
## Created on: Mon May 07 16:18:48 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
