######################################################################
##
## Filename: debounce.udo
## Created on: Sun May 06 16:22:47 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
