######################################################################
##
## Filename: sel5x32_1x32.udo
## Created on: Sun May 06 15:29:23 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
