######################################################################
##
## Filename: sig_gen_01Hz.udo
## Created on: Sun May 06 13:50:32 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
