######################################################################
##
## Filename: debounce.udo
## Created on: Sat May 05 13:18:00 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
