######################################################################
##
## Filename: automat.udo
## Created on: Mon Apr 09 15:09:25 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
