######################################################################
##
## Filename: binary_bcd.udo
## Created on: Sun May 06 11:03:31 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
