######################################################################
##
## Filename: clk_gen_1Hz_v3.udo
## Created on: Sun May 06 21:00:55 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
