######################################################################
##
## Filename: clk_gen_Hz_v2.udo
## Created on: Sun May 06 12:03:47 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
