######################################################################
##
## Filename: debounce.udo
## Created on: Sun May 06 11:42:17 Środkowoeuropejski czas letni 2018
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
